"""image column added

Revision ID: 996c5bd8b477
Revises: 3a4e1bf99bfd
Create Date: 2024-03-02 17:52:39.954293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996c5bd8b477'
down_revision = '3a4e1bf99bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
